import urllib.request
import csv
import json
import os

# Titanic dataset URL (standard 891 rows, 12 columns)
TITANIC_URL = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
CSV_FILENAME = "titanic.csv"
JS_FILENAME = "titanic_data.js"

def main():
    print(f"Downloading Titanic dataset from {TITANIC_URL}...")
    try:
        urllib.request.urlretrieve(TITANIC_URL, CSV_FILENAME)
        print(f"Dataset successfully saved as '{CSV_FILENAME}'.")
    except Exception as e:
        print(f"Error downloading dataset: {e}")
        return

    # Check file size and validity
    if not os.path.exists(CSV_FILENAME) or os.path.getsize(CSV_FILENAME) == 0:
        print("Error: Saved CSV file is empty or missing.")
        return

    # Read and parse CSV
    records = []
    print("Parsing CSV and generating local JavaScript database...")
    with open(CSV_FILENAME, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Parse data types
            parsed_row = {}
            
            # Integer fields
            for int_field in ["PassengerId", "Survived", "Pclass", "SibSp", "Parch"]:
                val = row.get(int_field, "")
                parsed_row[int_field] = int(val) if val.isdigit() else None
            
            # Float fields
            for float_field in ["Age", "Fare"]:
                val = row.get(float_field, "")
                if val:
                    try:
                        parsed_row[float_field] = float(val)
                    except ValueError:
                        parsed_row[float_field] = None
                else:
                    parsed_row[float_field] = None
            
            # String fields
            for str_field in ["Name", "Sex", "Ticket", "Cabin", "Embarked"]:
                val = row.get(str_field, "").strip()
                parsed_row[str_field] = val if val else None
                
            records.append(parsed_row)

    print(f"Parsed {len(records)} passenger records successfully.")

    # Write as JavaScript file
    with open(JS_FILENAME, mode='w', encoding='utf-8') as f:
        f.write("// Titanic Passenger Dataset - Autogenerated from CSV\n")
        f.write("window.titanicData = ")
        json.dump(records, f, indent=2)
        f.write(";\n")
    
    print(f"JavaScript database saved as '{JS_FILENAME}'. Ready for Web Hub!")

if __name__ == "__main__":
    main()
